Repository superagent-ai/superagent, pull requests merged in 2023-07, with the labels that each got.

#141 Update .env.example
  .env.example
Labels: enhancement

#142 Add support for passing in json inputs
  app/api/agents.py
  app/lib/agents/base.py
  app/lib/prompts.py
Labels: bug

#130 Firestore loader
  app/api/documents.py
  app/lib/documents.py
  app/lib/models/document.py
  poetry.lock
  prisma/migrations/20230628101303_firestore_document/migration.sql
  prisma/migrations/20230628102618_documents_metadata/migration.sql
  prisma/migrations/20230628132220_remove_document_metadata/migration.sql
  prisma/migrations/20230628135450_document_metadata/migration.sql
  prisma/schema.prisma
  pyproject.toml
Labels: enhancement

#143 Psychic
  .env.example
  .gitignore
  app/api/documents.py
  app/lib/documents.py
  app/lib/models/document.py
  poetry.lock
  prisma/migrations/20230702215550_psychic_document/migration.sql
  prisma/schema.prisma
  pyproject.toml
  ui/.env.example
  ui/.eslintrc.json
  ui/app/documents/client-page.js
  ui/package-lock.json
  ui/package.json
  ui/public/psychic-logo.png
Labels: enhancement

#146 Make Segement and Stripe optional
  ui/app/_components/providers.js
  ui/app/_components/sidebar.js
  ui/app/agents/client-page.js
  ui/app/agents/new/_components/agent-document.js
  ui/app/agents/new/_components/agent-tool.js
  ui/app/agents/new/client-page.js
  ui/app/api-tokens/client-page.js
  ui/app/documents/client-page.js
  ui/app/login/page.js
  ui/app/prompts/client-page.js
  ui/app/register/page.js
  ui/app/tools/client-page.js
  ui/lib/analytics.js
Labels: enhancement

#139 Add summary tool whenever a document is added to an Agent
  app/lib/agents/base.py
  app/lib/callbacks.py
  app/lib/tools.py
  ui/lib/prompts.js
Labels: enhancement

#148 Add support for Q&A over CSV files
  app/lib/agents/base.py
  poetry.lock
  prisma/migrations/20230703120810_csv_document/migration.sql
  prisma/schema.prisma
  pyproject.toml
  ui/app/documents/client-page.js
Labels: enhancement

#150 Update README
  README.md
  setup.sh
Labels: documentation

#152 Support ingestion of multiple URLS
  app/lib/documents.py
  ui/app/documents/client-page.js
Labels: enhancement

#153 Add Zapier NLA tool
  .env.example
  app/lib/agents/base.py
  app/lib/models/tool.py
  app/lib/tools.py
  prisma/migrations/20230704100732_zapier_nla_tool/migration.sql
  prisma/schema.prisma
  ui/app/tools/modal.js
  ui/lib/constants.js
Labels: enhancement

#154 Add `Agent-as-a-Tool`
  app/api/agents.py
  app/lib/agents/base.py
  app/lib/models/tool.py
  app/lib/tools.py
  poetry.lock
  prisma/migrations/20230704123514_agent_tool/migration.sql
  prisma/migrations/20230704155942_tool_description/migration.sql
  prisma/schema.prisma
  pyproject.toml
  ui/app/agents/[agentId]/client-page.js
  ui/app/agents/new/_components/agent-tool.js
  ui/app/tools/modal.js
Labels: enhancement

#155 Add support for OpenAPI tool
  app/lib/agents/base.py
  app/lib/models/tool.py
  app/lib/tools.py
  prisma/migrations/20230704173204_openapi_tool/migration.sql
  prisma/schema.prisma
  ui/app/agents/[agentId]/client-page.js
  ui/app/agents/new/_components/agent-tool.js
  ui/app/tools/modal.js
Labels: enhancement

#157 Design tweaks
  app/api/documents.py
  app/api/prompts.py
  app/api/tools.py
  ui/app/_components/container.js
  ui/app/_components/navigation.js
  ui/app/_components/search-bar.js
  ui/app/_components/sidebar.js
  ui/app/agents/[agentId]/client-page.js
  ui/app/agents/_components/card.js
  ui/app/agents/_components/row.js
  ui/app/agents/client-page.js
  ui/app/agents/new/client-page.js
  ui/app/api-tokens/client-page.js
  ui/app/client-page.js
  ui/app/documents/client-page.js
  ui/app/layout.js
  ui/app/login/page.js
  ui/app/logs/client-page.js
  ui/app/prompts/_components/card.js
  ui/app/prompts/_components/row.js
  ui/app/prompts/client-page.js
  ui/app/register/page.js
  ui/app/tools/client-page.js
  ui/lib/constants.js
Labels: enhancement

#161 Public agents
  prisma/migrations/20230705174614_agent_is_public/migration.sql
  prisma/schema.prisma
  ui/.env.example
  ui/app/agents/[agentId]/_components/nav.js
  ui/app/agents/[agentId]/client-page.js
  ui/app/share/client-page.js
  ui/app/share/page.js
Labels: enhancement

#164 Fix issue with client exception when user has not created an API token
  ui/app/agents/[agentId]/_components/nav.js
  ui/app/agents/[agentId]/client-page.js
Labels: bug

#166 Edit tool
  README.md
  app/api/tools.py
  app/lib/models/tool.py
  ui/app/tools/client-page.js
  ui/app/tools/modal.js
  ui/lib/api.js
Labels: enhancement

#176 Add support for claude-2
  app/lib/agents/base.py
  ui/Dockerfile
  ui/lib/llm.js
Labels: enhancement

#177 Add support for Bearer token in agent predict
  app/lib/auth/api.py
  fern/api/openapi/openapi.yml
Labels: bug

#178 Add fix for psychic document loading
  ui/app/documents/client-page.js
Labels: bug

#183 Update .gitignore to include codesandbox
  .gitignore
Labels: enhancement

#191 UI update
  README.md
  package-lock.json
  ui/app/_components/appbody.js
  ui/app/_components/navigation.js
  ui/app/_components/providers.js
  ui/app/agents/[agentId]/client-page.js
  ui/app/client-page.js
  ui/app/layout.js
  ui/app/login/page.js
  ui/app/register/page.js
  ui/lib/themes/glass.js
  ui/package-lock.json
  ui/package.json
Labels: enhancement

#196 Support Agent tags.
  app/api/tags.py
  app/lib/models/tag.py
  app/routers.py
  prisma/migrations/20230718121304_tags/migration.sql
  prisma/schema.prisma
Labels: enhancement

#197 Update OpenAPI spec
  fern/api/openapi/openapi.yml
Labels: enhancement

#199 Fix issue with background colour
  ui/app/_components/appbody.js
  ui/lib/constants.js
Labels: bug

#200 Add endpoint for patching a document
  app/api/documents.py
Labels: enhancement

#206 Update fern openapi spec
  fern/api/openapi/openapi.yml
Labels: enhancement

#181 Add support for deploying to replit
  .gitignore
  .replit
  README.md
  cpplib/libstdc++.la
  cpplib/libstdc++.so
  cpplib/libstdc++.so.6
  cpplib/libstdc++.so.6.0.29
  cpplib/libstdc++.so.6.0.29-gdb.py
  cpplib/libstdc++fs.la
  poetry.lock
  pyproject.toml
  replit.nix
  replit.sh
Labels: enhancement

#205 Add UI for creating tags
  app/api/agents.py
  ui/app/_components/filter-bar.js
  ui/app/agents/[agentId]/client-page.js
  ui/app/agents/_components/run.js
  ui/app/agents/client-page.js
  ui/app/agents/page.js
  ui/app/logs/client-page.js
  ui/app/tags/client-page.js
  ui/app/tags/page.js
  ui/app/tags/tag-picker.js
  ui/lib/api.js
  ui/lib/sidebar-menu.js
Labels: enhancement

#214 Fix issue with sharing agents
  app/api/agents.py
  ui/app/_components/providers.js
  ui/app/agents/[agentId]/_components/nav.js
Labels: bug

#222 Support SSO
  .env.example
  app/api/agents.py
  app/api/api_tokens.py
  app/api/auth.py
  app/api/documents.py
  app/api/prompts.py
  app/api/tags.py
  app/api/tools.py
  app/api/traces.py
  app/api/users.py
  app/lib/auth/prisma.py
  app/lib/models/auth.py
  poetry.lock
  prisma/migrations/20230723080842_user_oauth/migration.sql
  prisma/schema.prisma
  pyproject.toml
  ui/.env.example
  ui/app/layout.js
  ui/app/login/page.js
  ui/lib/api.js
  ui/lib/next-auth.js
Labels: enhancement

#223 Chatgpt plugins support
  app/lib/agents/base.py
  app/lib/tools.py
  prisma/migrations/20230726162604_plugins/migration.sql
  prisma/schema.prisma
  ui/app/tools/modal.js
  ui/lib/constants.js
Labels: enhancement

#226 Light mode
  ui/app/_components/appbody.js
  ui/app/_components/container.js
  ui/app/_components/main-nav.js
  ui/app/_components/providers.js
  ui/app/agents/[agentId]/client-page.js
  ui/app/agents/_components/run.js
  ui/app/agents/new/_components/agent-document.js
  ui/app/agents/new/_components/agent-tool.js
  ui/app/agents/new/_components/agent-type.js
  ui/app/client-page.js
  ui/app/login/page.js
  ui/app/logs/client-page.js
  ui/app/register/page.js
Labels: enhancement
