Repository superagent-ai/superagent, pull requests merged in 2023-08, with the labels that each got.

#230 Fix issue with creating API tokens
  app/api/api_tokens.py
  prisma/schema.prisma
  ui/lib/api.js
Labels: bug, ui

#232 Add possiblity to create different sessions when invoking agents
  app/api/agents.py
  app/lib/agents/agent.py
  app/lib/agents/base.py
  app/lib/models/agent.py
  prisma/migrations/20230801100402_agent_memory_session/migration.sql
  prisma/schema.prisma
  ui/lib/constants.js
Labels: enhancement

#235 Edit document title
  app/api/documents.py
  ui/app/documents/client-page.js
  ui/lib/api.js
Labels: enhancement

#238 Add Replit files
  .replit
  replit.nix
Labels: enhancement

#240 Remove vectors from Pinecone when deleting a document
  app/api/documents.py
  app/lib/vectorstores/pinecone.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#245 Add agent avatar
  app/api/agents.py
  app/lib/models/agent.py
  prisma/migrations/20230806185039_agent_avatar_url/migration.sql
  prisma/schema.prisma
  ui/app/agents/new/_components/agent-store-info.js
  ui/app/share/client-page.js
  ui/lib/constants.js
  ui/public/logo.png
Labels: enhancement

#246 Agent library
  app/api/agents.py
  app/api/api_tokens.py
  app/lib/models/agent.py
  prisma/migrations/20230806204122_agent_is_listed/migration.sql
  prisma/migrations/20230806211941_agent_description/migration.sql
  prisma/migrations/20230806215600_agent_shareable_token/migration.sql
  prisma/schema.prisma
  ui/app/agents/[agentId]/_components/nav.js
  ui/app/agents/_components/card.js
  ui/app/agents/new/client-page.js
  ui/app/client-page.js
  ui/app/page.js
  ui/app/share/client-page.js
  ui/lib/api.js
  ui/lib/sidebar-menu.js
Labels: enhancement

#244 Documents bug fix
  .env.example
  app/api/documents.py
  app/lib/documents.py
  app/lib/vectorstores/pinecone.py
Labels: enhancement

#248 Add possibility to change the description of a document
  app/api/documents.py
  app/lib/agents/base.py
  app/lib/models/document.py
  prisma/migrations/20230807202052_document_description/migration.sql
  prisma/schema.prisma
  ui/app/documents/client-page.js
Labels: enhancement

#257 Refactor data ingestion
  app/api/documents.py
  app/lib/documents.py
  app/lib/loaders/__init__.py
  app/lib/loaders/sitemap.py
  poetry.lock
  prisma/migrations/20230808152201_document_webpage/migration.sql
  prisma/migrations/20230809165852_document_stripe/migration.sql
  prisma/migrations/20230809204553_document_airtable/migration.sql
  prisma/migrations/20230810071652_document_sitemap/migration.sql
  prisma/schema.prisma
  pyproject.toml
  ui/.env.example
  ui/app/_components/search-bar.js
  ui/app/agents/[agentId]/client-page.js
  ui/app/datasources/_components/applications.js
  ui/app/datasources/_components/document-picker.js
  ui/app/datasources/_components/files.js
  ui/app/datasources/_components/upload-button.js
  ui/app/datasources/_components/webpages.js
  ui/app/datasources/client-page.js
  ui/app/datasources/page.js
  ui/app/documents/client-page.js
  ui/lib/datasources.js
  ui/lib/sidebar-menu.js
  ui/package-lock.json
  ui/package.json
  ui/public/airtable.jpeg
  ui/public/github.png
  ui/public/gong.jpeg
  ui/public/hubspot.png
  ui/public/intercom.png
  ui/public/salesforce.png
  ui/public/shopify.jpeg
  ui/public/stripe.jpeg
  ui/public/zendesk.png
Labels: enhancement

#262 Add ingestion of notion documents
  app/lib/documents.py
  poetry.lock
  prisma/migrations/20230811082703_notion_documents/migration.sql
  prisma/schema.prisma
  pyproject.toml
  ui/app/datasources/_components/applications.js
  ui/lib/datasources.js
  ui/public/notion.png
Labels: enhancement

#266 Fix issues with logging in with Github
  app/api/auth.py
  app/lib/auth/prisma.py
  ui/lib/sidebar-menu.js
Labels: bug

#270 Pinecone retrieval
  app/api/documents.py
  app/lib/agents/base.py
  app/lib/documents.py
  app/lib/splitters.py
  app/lib/tools.py
  app/lib/vectorstores/pinecone.py
Labels: enhancement

#272 Fix chat markdown
  ui/app/share/client-page.js
Labels: enhancement

#273 Add possibility for the chat interface to stream
  ui/app/share/client-page.js
Labels: bug

#277 Add possiblity to create sessions in shareable chat UI
  ui/app/share/client-page.js
  ui/lib/constants.js
  ui/lib/share-session.js
  ui/package-lock.json
  ui/package.json
Labels: enhancement

#281 Add functionality for embedding an agent to a external website.
  embed/dist/web.js
  embed/dist/web.js.LICENSE.txt
  embed/package-lock.json
  embed/package.json
  embed/src/index.js
  embed/test.html
  embed/webpack.config.js
  ui/app/agents/[agentId]/_components/nav.js
  ui/app/share/client-page.js
  ui/package-lock.json
  ui/package.json
Labels: enhancement

#285 Fix issues with running SDK with Api tokens
  app/lib/auth/prisma.py
Labels: bug

#294 Add user name/email to sidebar
  ui/app/_components/appbody.js
Labels: enhancement

#295 Add possibility to update agents
  ui/app/_components/appbody.js
  ui/app/agents/_components/card.js
  ui/app/agents/client-page.js
Labels: enhancement

#297 Add response models
  app/api/agent_documents.py
  app/api/agent_tools.py
  app/api/agents.py
  app/api/api_tokens.py
  app/api/auth.py
  app/api/documents.py
  app/api/prompts.py
  app/api/tags.py
  app/api/tools.py
  app/api/users.py
  app/lib/auth/prisma.py
  app/lib/models/agent.py
  app/lib/models/agent_document.py
  app/lib/models/agent_tool.py
  app/lib/models/api_token.py
  app/lib/models/auth.py
  app/lib/models/document.py
  app/lib/models/prompt.py
  app/lib/models/response.py
  app/lib/models/tag.py
  app/lib/models/tool.py
  app/lib/models/users.py
Labels: enhancement

#300 Add support for Langsmith
  .env.example
Labels: enhancement

#303 Update README.md
  README.md
Labels: enhancement

#304 Change Input to Textarea when adding URLs as datasources
  ui/app/datasources/_components/webpages.js
Labels: enhancement

#307 Add flag for human-in-the-loop
  prisma/migrations/20230822090845_agent_has_human_loop/migration.sql
  prisma/schema.prisma
Labels: enhancement

#317 Add warning message when no API token exists
  ui/app/agents/[agentId]/_components/nav.js
Labels: enhancement

#318 Add possibility to set cache in UI
  app/api/agents.py
  app/lib/agents/base.py
  app/lib/models/agent.py
  app/lib/models/response.py
  prisma/migrations/20230829091732_agent_has_cache/migration.sql
  prisma/schema.prisma
  ui/app/agents/[agentId]/client-page.js
  ui/app/agents/new/_components/agent-llm.js
  ui/app/agents/new/client-page.js
Labels: enhancement

#322 Add Pinecone vectorstore
  v2/.env.example
  v2/app/agents/base.py
  v2/app/api/agents.py
  v2/app/api/datasources.py
  v2/app/datasource/flow.py
  v2/app/tools/datasource.py
  v2/app/vectorstores/__init__.py
  v2/app/vectorstores/pinecone.py
  v2/poetry.lock
  v2/pyproject.toml
Labels: enhancement

#324 Add support for structured retrieval
  v2/app/agents/base.py
  v2/app/api/agents.py
  v2/app/datasource/flow.py
  v2/app/datasource/types.py
  v2/app/tools/datasource.py
Labels: enhancement

#325 Add support for RAG over JSON wiht pandas dataframe
  v2/app/agents/base.py
  v2/app/api/datasources.py
  v2/app/datasource/flow.py
  v2/app/datasource/loader.py
  v2/app/datasource/types.py
  v2/app/models/request.py
  v2/app/tools/datasource.py
  v2/poetry.lock
  v2/prisma/migrations/20230831081114_datasource_metadata/migration.sql
  v2/prisma/migrations/20230831092903_datasource_metadata_string/migration.sql
  v2/prisma/schema.prisma
  v2/pyproject.toml
Labels: enhancement

#326 Add Stripe Airbyte loader
  v2/app/datasource/loader.py
  v2/app/datasource/types.py
  v2/app/tools/datasource.py
  v2/prisma/migrations/20230831105225_add_datasource_types/migration.sql
  v2/prisma/schema.prisma
Labels: enhancement
